# Generated by Django 3.0.7 on 2020-06-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200610_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author2',
            new_name='author',
        ),
    ]
