# Generated by Django 3.0.7 on 2020-06-11 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200610_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catetegory',
            new_name='category',
        ),
    ]
